{{- if and (not .Values.useStatefulSet) .Values.persistence.enabled (not .Values.persistence.existingClaim) (eq .Values.persistence.type "pvc")}}
# PersistentVolumeClaim (PVC) Konfiguration für Grafana
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Name und Namespace des PVC
  name: {{ include "grafana.fullname" . }}
  namespace: {{ include "grafana.namespace" . }}
  labels:
    # Labels zur Identifikation des PVC
    {{- include "grafana.labels" . | nindent 4 }}
    {{- with .Values.persistence.extraPvcLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  # Anmerkungen für das PVC (optional)
  {{- with .Values.persistence.annotations  }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  # Finalizer zum Schutz vor versehentlichem Löschen
  {{- with .Values.persistence.finalizers  }}
  finalizers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # Zugriffsmethoden für das Volume (z. B. ReadWriteOnce)
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  # Anforderung an die Speichergröße
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  # Falls das Volume bereits existiert, seinen Namen zuordnen
  {{- if and (.Values.persistence.lookupVolumeName) (lookup "v1" "PersistentVolumeClaim" (include "grafana.namespace" .) (include "grafana.fullname" .)) }}
  volumeName: {{ (lookup "v1" "PersistentVolumeClaim" (include "grafana.namespace" .) (include "grafana.fullname" .)).spec.volumeName }}
  {{- end }}
  # Definiert die StorageClass (z. B. "fast-storage")
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  # Selektiert spezifische Labels, um ein bestimmtes Volume zu binden
  {{- with .Values.persistence.selectorLabels }}
  selector:
    matchLabels:
    {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
