{{- if or (and (not .Values.admin.existingSecret) 
               (not .Values.env.GF_SECURITY_ADMIN_PASSWORD__FILE) 
               (not .Values.env.GF_SECURITY_ADMIN_PASSWORD) 
               (not .Values.env.GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION)) 
          (and (default false .Values.ldap.enabled) 
               (not (default "" .Values.ldap.existingSecret))) }}
# Secret Konfiguration für Grafana
apiVersion: v1
kind: Secret
metadata:
  # Name und Namespace des Secrets
  name: {{ include "grafana.fullname" . }}
  namespace: {{ include "grafana.namespace" . }}
  labels:
    # Labels zur Identifikation des Secrets
    {{- include "grafana.labels" . | nindent 4 }}
  # Zusätzliche Anmerkungen (optional)
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
# Verschlüsselte Daten, z. B. Passwörter und Tokens
data:
  {{- include "grafana.secretsData" . | nindent 2 }}
{{- end }}
