{{- if .Values.serviceAccount.create }}
# ServiceAccount Konfiguration für Grafana
apiVersion: v1
kind: ServiceAccount
# Automatische Token-Mounting-Einstellungen
automountServiceAccountToken: {{ .Values.serviceAccount.autoMount | default .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  # Labels zur Identifikation des ServiceAccounts
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  # Zusätzliche Anmerkungen (optional)
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml . | nindent 4) $ }}
  {{- end }}
  # Name und Namespace des ServiceAccounts
  name: {{ include "grafana.serviceAccountName" . }}
  namespace: {{ include "grafana.namespace" . }}
{{- end }}
